name: Web Monitor

on:
  schedule:
    - cron: "*/2 * * * *"  # every 5 minutes
  workflow_dispatch:  # allow manual trigger

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run website check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_pages.py

      # Optional: Commit updated hash file to persist history
      - name: Commit updated hashes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add page_hashes.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update page hashes"
          git push
